version: '3.1'

services:
  mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: dev
      ports:
        - '27017:27017'
      volumes:
        - mongo_data:/data/db

  app:
    image: ghcr.io/defiantlabs/cosmos-proposals:latest
    restart: always
    environment:
      SLACK_BOT_TOKEN: xoxb-3901239539381-6270410294566-QDiRTRePKcCxc0em0I6AXowx
      MONGO_USERNAME: root
      MONGO_PASSWORD: dev
      MONGO_HOST: mongo
      MONGO_PORT: 27017

volumes:
  mongo_data: