# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/gov/v1beta1/proposals.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from cosmos.base import coin_pb2 as cosmos_dot_base_dot_coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"cosmos/gov/v1beta1/proposals.proto\x12\x12\x63osmos.gov.v1beta1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16\x63osmos/base/coin.proto\"2\n\x0cTextProposal\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x95\x01\n\x04Plan\x12\x0c\n\x04name\x18\x01 \x01(\t\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06height\x18\x03 \x01(\x03\x12\x0c\n\x04info\x18\x04 \x01(\t\x12\x37\n\x15upgraded_client_state\x18\x05 \x01(\x0b\x32\x14.google.protobuf.AnyB\x02\x18\x01\"e\n\x17SoftwareUpgradeProposal\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12&\n\x04plan\x18\x03 \x01(\x0b\x32\x18.cosmos.gov.v1beta1.Plan\"e\n\x12MsgExecuteContract\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08\x63ontract\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\x0c\x12 \n\x05\x66unds\x18\x05 \x03(\x0b\x32\x11.cosmos.base.Coin\"v\n\x1a\x43ommunityPoolSpendProposal\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x11\n\trecipient\x18\x03 \x01(\t\x12!\n\x06\x61mount\x18\x04 \x03(\x0b\x32\x11.cosmos.base.Coin\"o\n\x17ParameterChangeProposal\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x30\n\x07\x63hanges\x18\x03 \x03(\x0b\x32\x1f.cosmos.gov.v1beta1.ParamChange\";\n\x0bParamChange\x12\x10\n\x08subspace\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"s\n\x14\x43lientUpdateProposal\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x19\n\x11subject_client_id\x18\x03 \x01(\t\x12\x1c\n\x14substitute_client_id\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cosmos.gov.v1beta1.proposals_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAN'].fields_by_name['upgraded_client_state']._options = None
  _globals['_PLAN'].fields_by_name['upgraded_client_state']._serialized_options = b'\030\001'
  _globals['_TEXTPROPOSAL']._serialized_start=142
  _globals['_TEXTPROPOSAL']._serialized_end=192
  _globals['_PLAN']._serialized_start=195
  _globals['_PLAN']._serialized_end=344
  _globals['_SOFTWAREUPGRADEPROPOSAL']._serialized_start=346
  _globals['_SOFTWAREUPGRADEPROPOSAL']._serialized_end=447
  _globals['_MSGEXECUTECONTRACT']._serialized_start=449
  _globals['_MSGEXECUTECONTRACT']._serialized_end=550
  _globals['_COMMUNITYPOOLSPENDPROPOSAL']._serialized_start=552
  _globals['_COMMUNITYPOOLSPENDPROPOSAL']._serialized_end=670
  _globals['_PARAMETERCHANGEPROPOSAL']._serialized_start=672
  _globals['_PARAMETERCHANGEPROPOSAL']._serialized_end=783
  _globals['_PARAMCHANGE']._serialized_start=785
  _globals['_PARAMCHANGE']._serialized_end=844
  _globals['_CLIENTUPDATEPROPOSAL']._serialized_start=846
  _globals['_CLIENTUPDATEPROPOSAL']._serialized_end=961
# @@protoc_insertion_point(module_scope)
